### ISSUE TITLE
Networking does not work.

### ISSUE THREAD

**Issue by nmcain** [dahliaOS/buildroot#6]
Currently, the system uses WPA supplicant to configure networks, but it is unable to establish a connection. Ideally, it should be able to read wpa_supplicant and connect to a network using that file. Files can be added into the dahliaos-overlays, just treat it like any other Linux system.

**Comment by Griggorii** [comment]
Hello build problem help https://github.com/Griggorii/dahliaOS_iso_java-8-oracle/releases/tag/dahliaOS
Not found /usr/lib/xorg/Xorg.wrap version xserver_xorg-server-1.20.9

**Comment by bleonard252** [comment]
Hey, this is fixed now, right?

**Comment by nmcain** [comment]
haha, it is!
